<?php

namespace MovieListBundle\Repository;

/**
 * MoviesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoviesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByExpiryDate($expirydate)
    {
        $qb = $this->createQueryBuilder('m')
            ->where('m.expirydate > :expirydate')
            ->setParameter('expirydate', $expirydate)
            ->getQuery();

        return $qb->getResult();
    }
}
